name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stage

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        #run: pytest --maxfail=1 --disable-warnings -q

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Production server (main branch)..."
          # Example: ssh into server and deploy
          # ssh user@prod-server "cd /app && git pull && systemctl restart fastapi"

      - name: Deploy to Stage Server
        if: github.ref == 'refs/heads/stage'
        run: |
          echo "Deploying to Staging server (stage branch)..."
          # Example: ssh into staging server
          # ssh user@stage-server "cd /app && git pull && systemctl restart fastapi"
